import type { Metadata } from 'next'
import '../../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function ProductDetailsLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      {children}
      <h2>Features Products</h2>
      <h2>Carousel</h2>
    </>
  )
}
