import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/header'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Toaster />
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {/* <Header /> */}
          <header
            style={{
              backgroundColor: 'skyblue',
              padding: '1rem'
            }}
          >
            <p>Header</p>
          </header>
          {children}
          <footer
            style={{
              backgroundColor: 'salmon',
              padding: '1rem'
            }}
          >
            <p>Footer</p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  )
}
